In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4, 4]

In [4]:
l

[1, 2, 3, 4, 4]

In [5]:
type(l)

list

In [6]:
a = np.array(l)

In [7]:
a

array([1, 2, 3, 4, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2 = np.array([[[1, 2, 3], [4, 5, 6]]])

In [12]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a

array([1, 2, 3, 4, 4])

In [14]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [16]:
a.ndim

1

In [17]:
a1.ndim

2

In [18]:
a2.ndim

3

In [19]:
a3 = np.array([[[[1, 2, 3], [4, 5, 6]]]])

In [20]:
a3.ndim

4

In [21]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [22]:
a3.ndim

3

In [23]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [28]:
l = [1, 2, 3, 4, 5]

In [29]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [30]:
l1 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [31]:
np.matrix(l1)

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [32]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [33]:
l

[1, 2, 3, 4, 5]

In [34]:
a = np.array(l)

In [35]:
m = np.matrix(l)

In [36]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [37]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [38]:
np.asanyarray(m)

matrix([[1, 2, 3, 4, 5]])

In [39]:
a

array([1, 2, 3, 4, 5])

In [40]:
a1 = a

In [41]:
a1 

array([1, 2, 3, 4, 5])

In [42]:
a

array([1, 2, 3, 4, 5])

In [43]:
a[0]=10

In [44]:
a

array([10,  2,  3,  4,  5])

In [45]:
a1

array([10,  2,  3,  4,  5])

In [46]:
a1[3]=50

In [47]:
a

array([10,  2,  3, 50,  5])

In [48]:
a2 = np.copy(a)

In [52]:
a2

array([10,  2, 30, 50,  5])

In [50]:
a2[2]=30

In [51]:
a

array([10,  2,  3, 50,  5])

# 2:05

In [1]:
import numpy as np

In [2]:
np.fromfunction(lambda i, j : i==j, (3, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [3]:
np.random.rand(2, 3)

array([[0.32784532, 0.07566623, 0.83252121],
       [0.64906028, 0.68183135, 0.76075259]])

In [4]:
np.random.rand(2, 2, 3)

array([[[0.84488128, 0.76475695, 0.57536695],
        [0.42535305, 0.11892779, 0.17952291]],

       [[0.90353027, 0.95525372, 0.93132113],
        [0.12848939, 0.891357  , 0.18672368]]])

In [5]:
np.random.rand(3, 3, 3)

array([[[0.58623251, 0.80482495, 0.03928005],
        [0.88088485, 0.26820028, 0.43732448],
        [0.2453926 , 0.79145301, 0.37030293]],

       [[0.53179894, 0.1509666 , 0.46597571],
        [0.88862775, 0.95985519, 0.79928304],
        [0.70526587, 0.67020541, 0.37170051]],

       [[0.4571145 , 0.21014856, 0.55005773],
        [0.4547668 , 0.86600756, 0.34418721],
        [0.56932405, 0.16853486, 0.62536164]]])

In [12]:
np.random.rand(2, 3, 4)

array([[[0.15149807, 0.73007262, 0.83840199, 0.28303693],
        [0.33730379, 0.55010695, 0.23432517, 0.24361671],
        [0.97058338, 0.96913563, 0.85919644, 0.91232223]],

       [[0.17234667, 0.50151418, 0.16368859, 0.08079101],
        [0.05527595, 0.80016916, 0.01741944, 0.59137011],
        [0.91100063, 0.29220322, 0.22199962, 0.70871971]]])

In [11]:
np.random.randint(1, 20, (4, 4))

array([[14, 17,  8, 18],
       [14,  3,  2, 17],
       [10,  2, 15,  3],
       [15,  8,  3,  5]])

In [13]:
np.random.randint(1, 20, (4, 4, 2))

array([[[17, 11],
        [ 8, 10],
        [ 4,  4],
        [19, 19]],

       [[ 6,  2],
        [13, 14],
        [14,  3],
        [16, 12]],

       [[ 3,  2],
        [ 1, 12],
        [10, 14],
        [17, 17]],

       [[ 3, 15],
        [10, 11],
        [ 7, 18],
        [ 3,  1]]])

In [15]:
np.random.randint(0, 19, (3, 3, 4))

array([[[ 0, 18, 16,  5],
        [ 6, 17, 18,  6],
        [16, 16,  5, 14]],

       [[15,  9,  8,  0],
        [14,  1, 17, 16],
        [16, 10, 18, 17]],

       [[ 7,  9,  7,  6],
        [11,  9, 12,  1],
        [16,  2,  2, 13]]])

In [16]:
np.random.randn(3, 4)

array([[-0.29374312, -1.04726833,  1.22162197, -0.113374  ],
       [-0.49864825, -0.44658988,  0.18190231, -1.63236155],
       [ 0.26208707,  1.54546839,  1.03885949,  0.50786097]])

In [17]:
d = np.random.randn(3, 4)

In [19]:
import pandas as pd

In [21]:
pd.DataFrame(d)

0         1         2         3
0  0.232983 -2.580934 -0.528489  0.313525
1 -0.311449  0.103333 -0.109302 -0.409995
2 -0.050835 -0.049378 -0.188227  0.887001

In [23]:
e = np.random.randn(3, 3, 4)

In [24]:
pd.DataFrame(e)

ValueError: Must pass 2-d input. shape=(3, 3, 4)

In [27]:
d1 = np.random.rand(3, 4, 5)

In [31]:
pd.DataFrame(d1.reshape(10, -1))

0         1         2         3         4         5
0  0.692028  0.890082  0.960003  0.114363  0.572019  0.687006
1  0.378784  0.247173  0.054595  0.627513  0.536355  0.914068
2  0.333371  0.684571  0.631018  0.124481  0.049794  0.329032
3  0.588787  0.013298  0.226994  0.199892  0.263749  0.521324
4  0.215689  0.190001  0.750770  0.433235  0.687083  0.138323
5  0.054199  0.483693  0.528410  0.494355  0.007708  0.899540
6  0.449387  0.803627  0.555810  0.829140  0.202616  0.612500
7  0.755319  0.238566  0.749608  0.980288  0.220429  0.252294
8  0.336493  0.913353  0.732047  0.072475  0.950716  0.560178
9  0.256134  0.550798  0.023489  0.460562  0.532595  0.697001

# Numpy and Graphs class 40

In [33]:
import numpy as np

In [34]:
range(10)

range(0, 10)

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(.5, 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [39]:
np.arange(4, -4, -0.5)

array([ 4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. , -0.5, -1. ,
       -1.5, -2. , -2.5, -3. , -3.5])

In [40]:
np.arange(0.5, 5, .25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [43]:
list(np.linspace(0, 5, 15))

[0.0,
 0.35714285714285715,
 0.7142857142857143,
 1.0714285714285714,
 1.4285714285714286,
 1.7857142857142858,
 2.142857142857143,
 2.5,
 2.857142857142857,
 3.2142857142857144,
 3.5714285714285716,
 3.928571428571429,
 4.285714285714286,
 4.642857142857143,
 5.0]

In [44]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [45]:
np.logspace(1, 5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.zeros((3, 5, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [50]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [57]:
np.ones((3, 4, 2))*3

array([[[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]])

In [56]:
len(a)

3

In [60]:
np.empty((2, 3))

array([[6.95214975e-310, 6.95214975e-310, 6.95214975e-310],
       [6.95214975e-310, 6.95214975e-310, 6.95214975e-310]])

In [62]:
a = np.eye(4, 4)

In [63]:
pd.DataFrame(a)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [65]:
a.shape

(4, 4)

In [66]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
a.size

16

In [70]:
a.ndim

2

In [71]:
a = np.random.rand(3, 4)

In [72]:
pd.DataFrame(a)

0         1         2         3
0  0.116645  0.255428  0.082775  0.620914
1  0.696731  0.545227  0.969655  0.550172
2  0.365341  0.996716  0.662887  0.360389

In [73]:
a

array([[0.11664549, 0.2554277 , 0.08277502, 0.62091433],
       [0.69673121, 0.54522655, 0.96965545, 0.5501719 ],
       [0.36534121, 0.99671595, 0.66288725, 0.36038928]])

In [74]:
a[1][1]

0.5452265532865572

In [76]:
a[1][3]

0.550171899041139

In [77]:
a[0:2, 0:2]

array([[0.11664549, 0.2554277 ],
       [0.69673121, 0.54522655]])

In [78]:
a[[0, 1], 0:2]

array([[0.11664549, 0.2554277 ],
       [0.69673121, 0.54522655]])

In [79]:
a

array([[0.11664549, 0.2554277 , 0.08277502, 0.62091433],
       [0.69673121, 0.54522655, 0.96965545, 0.5501719 ],
       [0.36534121, 0.99671595, 0.66288725, 0.36038928]])

In [84]:
a[[1, 2], 3]

array([0.5501719 , 0.36038928])

In [87]:
m1 = np.random.randint(1, 3, (3, 3))

In [88]:
m1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [89]:
m2 = np.random.randint(2, 4, (3, 3))

In [90]:
m2

array([[3, 2, 3],
       [2, 2, 3],
       [3, 2, 2]])

In [91]:
m1*m2

array([[3, 4, 3],
       [2, 2, 3],
       [6, 4, 2]])

In [92]:
m1@m2

array([[10,  8, 11],
       [ 8,  6,  8],
       [13, 10, 14]])

In [93]:
pow(m1, 2)

array([[1, 4, 1],
       [1, 1, 1],
       [4, 4, 1]], dtype=int32)

In [94]:
pow(m2, 2)

array([[9, 4, 9],
       [4, 4, 9],
       [9, 4, 4]], dtype=int32)

In [95]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [96]:
np.sqrt(m2)

array([[1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.41421356]])

In [97]:
np.log(m1)

array([[0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.69314718, 0.69314718, 0.        ]])

In [98]:
np.log(m2)

array([[1.09861229, 0.69314718, 1.09861229],
       [0.69314718, 0.69314718, 1.09861229],
       [1.09861229, 0.69314718, 0.69314718]])

In [99]:
np.log10(m1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [100]:
np.log10(m2)

array([[0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.30103   ]])

In [102]:
np.exp(m1, m2)

TypeError: ufunc 'exp' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [103]:
np.exp(m1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [104]:
np.exp(m2)

array([[20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692,  7.3890561 ,  7.3890561 ]])

In [105]:
pow(m1, 2)

array([[1, 4, 1],
       [1, 1, 1],
       [4, 4, 1]], dtype=int32)

In [106]:
m1**2

array([[1, 4, 1],
       [1, 1, 1],
       [4, 4, 1]], dtype=int32)